"""initial schema

Revision ID: c58f00ff0d67
Revises: 
Create Date: 2026-08-14 18:51:24.087472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58f00ff0d67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('otp',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'MENTOR', 'PROGRAM_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_level', sa.Enum('SCHOOL_DEPARTMENT', 'CAMPUS', 'INTER_CAMPUS', 'STATE', 'NATIONAL', 'INTERNATIONAL', name='eventlevel'), nullable=False),
    sa.Column('participation_category', sa.Enum('PARTICIPANT', 'POSITION_HOLDER', 'ORGANISER_LEAD', 'VOLUNTEER_CORE_TEAM', 'REPRESENTATIVE', name='participationcategory'), nullable=False),
    sa.Column('event_start_date', sa.Date(), nullable=False),
    sa.Column('event_end_date', sa.Date(), nullable=False),
    sa.Column('organising_body', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('team', sa.Boolean(), nullable=False),
    sa.Column('supporting_link', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'NEEDS_INFO', 'APPROVED_PUBLISHED', 'REJECTED', 'DISPUTED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_by_mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluated_by_mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('claim_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'NEEDS_INFO', 'APPROVED_PUBLISHED', 'REJECTED', 'DISPUTED', 'CLOSED', name='claimstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'NEEDS_INFO', 'APPROVED_PUBLISHED', 'REJECTED', 'DISPUTED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'roll_number', name='uq_claim_roll_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_team_members')
    op.drop_table('claim_status_history')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
